version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpassword123
      - DB_NAME=event_db
      - DB_DIALECT=mysql
      - MYSQL_PORT=3306
      - JWT_SECRET=movinsync@123
      - PORT=5000
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3308:3306" 
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword123
      - MYSQL_DATABASE=event_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
